#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-only
set -euo pipefail

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
source "$ROOT/ci/pins.env"
CACHE_DIR=${HONK_CACHE_DIR:-"$ROOT/artifacts/cache"}
WORK_DIR=${HONK_WORK_DIR:-"$ROOT/.cache/doona-work"}
mkdir -p "$CACHE_DIR" "$(dirname "$WORK_DIR")"
rm -rf "$WORK_DIR"
mkdir -p "$WORK_DIR"

touch "$WORK_DIR/case-sensitivity-probe"
if test -e "$WORK_DIR/CASE-SENSITIVITY-PROBE"; then
	echo 'Doona source contains case-colliding paths; build on Linux or a case-sensitive volume.' >&2
	exit 1
fi
rm "$WORK_DIR/case-sensitivity-probe"

for tool in git node corepack sha256sum tar rg find; do
	command -v "$tool" >/dev/null || { echo "Missing required tool: $tool" >&2; exit 1; }
done

git clone --quiet "$DOONA_REPOSITORY" "$WORK_DIR/source"
git -C "$WORK_DIR/source" checkout --quiet "$DOONA_COMMIT"
test "$(git -C "$WORK_DIR/source" rev-parse HEAD)" = "$DOONA_COMMIT"
test "$(sha256sum "$ROOT/$DOONA_PATCH" | cut -d' ' -f1)" = "$DOONA_PATCH_SHA256"
git -C "$WORK_DIR/source" apply --check "$ROOT/$DOONA_PATCH"
git -C "$WORK_DIR/source" apply "$ROOT/$DOONA_PATCH"

cd "$WORK_DIR/source"
SOURCE_DOONA_VERSION=$(node -p "JSON.parse(require('fs').readFileSync('package.json', 'utf8')).version")
test "$SOURCE_DOONA_VERSION" = "$DOONA_VERSION"
corepack pnpm@"$DOONA_PNPM_VERSION" install --frozen-lockfile
VITE_OPENWRT_HONK=1 corepack pnpm@"$DOONA_PNPM_VERSION" build
test -s dist/index.html
! rg -n 'MockBackend|mockBackend|mock-backend' dist

STAGE="$WORK_DIR/stage/doona"
rm -rf "$WORK_DIR/stage"
mkdir -p "$STAGE"
cp -a dist/. "$STAGE/"
for file in LICENSE NOTICE CHANGELOG.md README.md; do
	test -f "$WORK_DIR/source/$file"
	cp "$WORK_DIR/source/$file" "$STAGE/$file"
done
node tools/notices.mjs "$STAGE"
test -s "$STAGE/THIRD-PARTY-NOTICES.txt"
test -d "$STAGE/LICENSES"
test -n "$(find "$STAGE/LICENSES" -type f -print -quit)"
cat > "$STAGE/SOURCE" <<EOF
Repository: $DOONA_REPOSITORY
Commit: $DOONA_COMMIT
Version: $DOONA_VERSION
Build patch SHA256: $DOONA_PATCH_SHA256
Build: VITE_OPENWRT_HONK=1 corepack pnpm@$DOONA_PNPM_VERSION build
Status: OpenWrt same-origin API; mock fallback and mock backend chunk removed
EOF

STAGE_ARCHIVE="$WORK_DIR/$DOONA_ARCHIVE"
tar --sort=name --mtime='UTC 2026-01-01' --owner=0 --group=0 --numeric-owner -czf "$STAGE_ARCHIVE" -C "$WORK_DIR/stage" doona
install -m 0644 "$STAGE_ARCHIVE" "$CACHE_DIR/$DOONA_ARCHIVE"
DOONA_SHA256=$(sha256sum "$CACHE_DIR/$DOONA_ARCHIVE" | cut -d' ' -f1)
cat > "$ROOT/luci-app-honk/generated-doona-stage.mk" <<EOF
# Generated by ci/build-doona.sh; do not commit.
PKG_SOURCE:=$DOONA_ARCHIVE
PKG_SOURCE_URL:=https://github.com/kenzok8/openwrt-honk/releases/download/staging
PKG_SOURCE_SUBDIR:=doona
PKG_HASH:=$DOONA_SHA256
EOF
printf 'Doona archive: %s\nSHA256: %s\n' "$CACHE_DIR/$DOONA_ARCHIVE" "$DOONA_SHA256"
