#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-only
set -euo pipefail

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
source "$ROOT/ci/pins.env"
if test "$(uname -s)" != Linux || test "$(uname -m)" != x86_64; then
	echo 'The pinned Honk core build requires Linux x86_64.' >&2
	exit 1
fi
CACHE_DIR=${HONK_CACHE_DIR:-"$ROOT/artifacts/cache"}
WORK_DIR=${HONK_WORK_DIR:-"$ROOT/.cache/core-work"}
CARGO_HOME=${CARGO_HOME:-"$ROOT/.cache/cargo"}
export CARGO_HOME
mkdir -p "$CACHE_DIR" "$WORK_DIR" "$CARGO_HOME/bin"

for tool in git rustup cargo zig sha256sum tar readelf curl zstd rg; do
	command -v "$tool" >/dev/null || { echo "Missing required tool: $tool" >&2; exit 1; }
done
test "$(zig version)" = "$ZIG_VERSION" || { echo "Expected Zig $ZIG_VERSION." >&2; exit 1; }
test -f "$ROOT/luci-app-honk/generated-doona-stage.mk" || { echo 'Run ci/build-doona.sh first.' >&2; exit 1; }
DOONA_ARCHIVE_PATH="$CACHE_DIR/$DOONA_ARCHIVE"
test -s "$DOONA_ARCHIVE_PATH" || { echo "Missing staged Doona archive: $DOONA_ARCHIVE_PATH" >&2; exit 1; }
DOONA_SHA256=$(sha256sum "$DOONA_ARCHIVE_PATH" | cut -d' ' -f1)

rm -rf "$WORK_DIR/source"
git clone --quiet "$CORE_REPOSITORY" "$WORK_DIR/source"
git -C "$WORK_DIR/source" checkout --quiet "$CORE_COMMIT"
test "$(git -C "$WORK_DIR/source" rev-parse HEAD)" = "$CORE_COMMIT"
test -f "$WORK_DIR/source/Cargo.lock"
test "$(sha256sum "$ROOT/$CORE_PATCH" | cut -d' ' -f1)" = "$CORE_PATCH_SHA256"
git -C "$WORK_DIR/source" apply --check "$ROOT/$CORE_PATCH"
git -C "$WORK_DIR/source" apply "$ROOT/$CORE_PATCH"

TOOLCHAIN=$(sed -n 's/^channel = "\([^"]*\)"/\1/p' "$WORK_DIR/source/rust-toolchain.toml")
test -n "$TOOLCHAIN"
rustup toolchain install "$TOOLCHAIN" --profile minimal --component rust-src
rustup toolchain install nightly-2026-07-20 --profile minimal --component rust-src --component llvm-tools
rustup target add --toolchain "$TOOLCHAIN" x86_64-unknown-linux-musl
rg -q '^native-api\s*=' "$WORK_DIR/source/crates/honk-core/Cargo.toml"
rg -q '^clash-api\s*=' "$WORK_DIR/source/crates/honk-core/Cargo.toml"
rg -q '^ebpf\s*=' "$WORK_DIR/source/crates/honk-core/Cargo.toml"
test -x "$WORK_DIR/source/ci/zigcc"
test -x "$WORK_DIR/source/ci/zigcxx"
test -x "$WORK_DIR/source/ci/zig-bindgen-env"

BPF_LINKER_TGZ="$WORK_DIR/bpf-linker.tar.zst"
BPF_LINKER_URL="https://github.com/aya-rs/bpf-linker/releases/download/v$BPF_LINKER_VERSION/bpf-linker-x86_64-unknown-linux-musl.tar.zst"
curl -fL "$BPF_LINKER_URL" -o "$BPF_LINKER_TGZ"
test "$(sha256sum "$BPF_LINKER_TGZ" | cut -d' ' -f1)" = "$BPF_LINKER_SHA256"
zstd -dc "$BPF_LINKER_TGZ" | tar -xf - -C "$CARGO_HOME/bin"
chmod +x "$CARGO_HOME/bin/bpf-linker"
export PATH="$CARGO_HOME/bin:$PATH"
BPF_LINKER_REPORTED_VERSION=$("$CARGO_HOME/bin/bpf-linker" --version)
case "$BPF_LINKER_REPORTED_VERSION" in
	"bpf-linker $BPF_LINKER_VERSION"|"bpf-linker 0.0.0") ;;
	*) echo "Unexpected bpf-linker self-reported version: $BPF_LINKER_REPORTED_VERSION" >&2; exit 1 ;;
esac

cd "$WORK_DIR/source/crates/honk-ebpf"
cargo +nightly-2026-07-20 build --locked --release -Zbuild-std=core --target bpfel-unknown-none
readelf -S target/bpfel-unknown-none/release/honk-ebpf | rg -q '\.BTF'

export ZIGCC_TARGET=x86_64-linux-musl
export CC_x86_64_unknown_linux_musl="$WORK_DIR/source/ci/zigcc"
export CXX_x86_64_unknown_linux_musl="$WORK_DIR/source/ci/zigcxx"
export CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER="$WORK_DIR/source/ci/zigcc"
export CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_RUSTFLAGS='-C link-self-contained=no'
BINDGEN_EXTRA_CLANG_ARGS=$("$WORK_DIR/source/ci/zig-bindgen-env" x86_64-linux-musl)
export BINDGEN_EXTRA_CLANG_ARGS
cd "$WORK_DIR/source"
cargo +"$TOOLCHAIN" build --locked --release -p honk-core --no-default-features --features 'clash-api,ebpf,rprx,native-api' --target x86_64-unknown-linux-musl

BIN=target/x86_64-unknown-linux-musl/release/honk-core
test -x "$BIN"
readelf -h "$BIN" | rg -q 'Advanced Micro Devices X86-64'
STAGE="$WORK_DIR/stage/honk-core-$CORE_COMMIT"
rm -rf "$WORK_DIR/stage"
mkdir -p "$STAGE/doona"
install -m 0755 "$BIN" "$STAGE/honk-core"
cp LICENSE README.md "$STAGE/"
tar -xzf "$DOONA_ARCHIVE_PATH" --strip-components=1 -C "$STAGE/doona"
if grep -q '^Build patch: /' "$STAGE/doona/SOURCE"; then
	sed -i.bak 's#^Build patch: .*#Build patch: ci/patches/doona-openwrt.patch#' "$STAGE/doona/SOURCE"
	rm -f "$STAGE/doona/SOURCE.bak"
fi

ARCHIVE_PATH="$CACHE_DIR/$CORE_ARCHIVE"
tar --sort=name --mtime='UTC 2026-01-01' --owner=0 --group=0 --numeric-owner -czf "$ARCHIVE_PATH" -C "$WORK_DIR/stage" "honk-core-$CORE_COMMIT"
CORE_SHA256=$(sha256sum "$ARCHIVE_PATH" | cut -d' ' -f1)
CORE_VERSION=$(sed -n 's/^version = "\([^"]*\)"/\1/p' "$WORK_DIR/source/Cargo.toml" | head -n 1)
DOONA_VERSION_FROM_SOURCE=$(sed -n 's/^Version: //p' "$STAGE/doona/SOURCE")
DOONA_VERSION=${DOONA_VERSION_FROM_SOURCE:-$DOONA_VERSION}
test -n "$CORE_VERSION"
test -n "$DOONA_VERSION"
cat > "$ROOT/honk/generated-stage.mk" <<EOF
# Generated by ci/build-core.sh; do not commit.
PKG_SOURCE:=$CORE_ARCHIVE
PKG_SOURCE_URL:=https://github.com/kenzok8/openwrt-honk/releases/download/staging
PKG_SOURCE_SUBDIR:=honk-core-$CORE_COMMIT
PKG_HASH:=$CORE_SHA256
HONK_CORE_PATCH_SHA256:=$CORE_PATCH_SHA256
EOF
cat > "$ROOT/honk/generated-provenance.json" <<EOF
{
  "core": {
    "repository": "$CORE_REPOSITORY",
    "commit": "$CORE_COMMIT",
    "patch_sha256": "$CORE_PATCH_SHA256",
    "version": "$CORE_VERSION"
  },
  "doona": {
    "repository": "$DOONA_REPOSITORY",
    "version": "$DOONA_VERSION",
    "source_commit": "$DOONA_COMMIT",
    "patch_sha256": "$DOONA_PATCH_SHA256",
    "artifact_sha256": "$DOONA_SHA256"
  },
  "core_archive": {
    "filename": "$CORE_ARCHIVE",
    "sha256": "$CORE_SHA256"
  },
  "runtime_requirements": {
    "kernel_btf_path": "/sys/kernel/btf/vmlinux",
    "sdk_btf_verified": false
  },
  "bpf_linker": {
    "release_version": "$BPF_LINKER_VERSION",
    "reported_version": "$BPF_LINKER_REPORTED_VERSION",
    "sha256": "$BPF_LINKER_SHA256"
  }
}
EOF
printf 'Core archive: %s\nSHA256: %s\n' "$ARCHIVE_PATH" "$CORE_SHA256"
